//
//  language.swift
//  iSub
//
//  Created by CryRose on 6/12/17.
//  Copyright © 2017 tansociu. All rights reserved.
//

import Foundation

public class LangConstants {
    
    static let arrLang = ["Afrikaans", "Albanian",
    "Amharic", "Arabic", "Armenian",
    "Azerbaijani", "Basque", "Belarusian",
    "Bengali", "Bosnian", "Bulgarian",
    "Burmese", "Catalan", "Cebuano",
    "Chinese", "Corsican", "Croatian", "Czech",
    "Danish", "Dutch", "English",
    "Esperanto", "Estonian", "Finnish",
    "French", "Galician", "Georgian",
    "German", "Greek", "Gujarati",
    "Haitian", "Hausa", "Hawaiian",
    "Hebrew", "Hindi", "Hmong",
    "Hungarian", "Icelandic", "Igbo",
    "Indonesian", "Irish", "Italian",
    "Japanese", "Javanese", "Kannada",
    "Kazakh", "Khmer", "Korean",
    "Kurdish", "Kyrgyz", "Lao",
    "Latin", "Latvian", "Lithuanian",
    "Luxembourgish", "Macedonian", "Malagasy",
    "Malay", "Malayalam", "Maltese",
    "Maori", "Marathi", "Mongolian",
    "Nepali", "Norwegian", "Nyanja",
    "Pashto", "Persian", "Polish",
    "Portuguese", "Punjabi", "Romanian",
    "Russian", "Samoan", "Scottish Gaelic",
    "Serbian", "Shona", "Sindhi",
    "Sinhala", "Slovak", "Slovenian",
    "Somali", "Southern Sotho", "Spanish",
    "Sundanese", "Swahili", "Swedish",
    "Tajik", "Tamil",
    "Telugu", "Thai", "Turkish",
    "Ukrainian", "Urdu", "Uzbek",
    "Vietnamese", "Welsh", "Xhosa",
    "Yiddish", "Yoruba", "Zulu"
    ]
    
    static let arrCode = ["af", "sq",
    "am", "ar", "hy",
    "az", "eu", "be",
    "bn", "bs", "bg",
    "my", "ca", "ceb",
    "zh-CN", "co", "hr", "cs",
    "da", "nl", "en",
    "eo", "et", "fi",
    "fr", "gl", "ka",
    "de", "el", "gu",
    "ht", "ha", "haw",
    "iw", "hi", "hmn",
    "hu", "is", "ig",
    "id", "ga", "it",
    "ja", "jw", "kn",
    "kk", "km", "ko",
    "ku", "ky", "lo",
    "la", "lv", "lt",
    "lb", "mk", "mg",
    "ms", "ml", "mt",
    "mi", "mr", "mn",
    "ne", "no", "ny",
    "ps", "fa", "pl",
    "pt", "pa", "ro",
    "ru", "sm", "gd",
    "sr", "sn", "sd",
    "si", "sk", "sl",
    "so", "st", "es",
    "su", "sw", "sv",
    "tg", "ta",
    "te", "th", "tr",
    "uk", "ur", "uz",
    "vi", "cy", "xh",
    "yi", "yo", "zu"
    ]
    
    static let arrFlag = ["flag_south_africa", "flag_albania",
    "flag_amharic", "flag_saudi_arabia", "flag_armenia",
    "flag_azerbaijan", "flag_basque", "flag_belarus",
    "flag_bangladesh", "flag_bosnia_herzegovina", "flag_bulgarian",
    "flag_burmese", "flag_catalan", "flag_philippines",
    "flag_china", "flag_corsican", "flag_croatia", "flag_czech",
    "flag_dania", "flag_netherlands", "flag_english",
    "flag_esperanto", "flag_estonia", "flag_finland",
    "flag_france", "flag_galician", "flag_georgia",
    "flag_germany", "flag_greek", "flag_india",
    "flag_haiti", "flag_nigeria", "flag_hawaiian",
    "flag_israel", "flag_india", "flag_china",
    "flag_hungary", "flag_iceland", "flag_nigeria",
    "flag_indonesia","flag_ireland", "flag_italy",
    "flag_japan", "flag_indonesia", "flag_india",
    "flag_kazakh", "flag_cambodia", "flag_korea",
    "flag_kurdish", "flag_kyrgyz", "flag_laos",
    "flag_latin", "flag_latvia", "flag_lithuania",
    "flag_luxembourgish", "flag_macedonia", "flag_malagasy",
    "flag_malaysia", "flag_malayalam", "flag_maltese",
    "flag_maori", "flag_india", "flag_mongolia",
    "flag_nepali","flag_norway", "flag_nyanja",
    "flag_pashto", "flag_iran", "flag_polish",
    "flag_portugal", "flag_india", "flag_romania",
    "flag_russia", "flag_samoan", "flag_scottish_gaelic",
    "flag_serbia", "flag_shona", "flag_sindhi",
    "flag_sri_lanka", "flag_slovakia", "flag_slovenia",
    "flag_somali", "flag_southern_sotho", "flag_spain",
    "flag_sundanese", "flag_south_africa", "flag_sweden",
    "flag_tajik", "flag_sri_lanka",
    "flag_india", "flag_thailand", "flag_turkey",
    "flag_ukraine", "flag_pakistan", "flag_uzbek",
    "flag_vietnam", "flag_welsh", "flag_xhosa",
    "flag_yiddish", "flag_nigeria", "flag_south_africa"
    ]
}
